table dClientes
	lineageTag: b5c00b83-78d4-4cfe-86e3-6276d046eef8

	column 'ID Cliente'
		dataType: string
		lineageTag: 3ffb3831-8e3e-458e-a5c5-ac82a506a814
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 73cc8a7f-ef61-434b-8b39-9864c24f68c2
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: df63f9c3-d550-45db-8691-9e29022dfcfd
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: cf7997a2-13d8-4fed-a666-99a1ddc8770d
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: edadee08-eab7-44d0-b877-72376c3fc5fa
		summarizeBy: none
		sourceColumn: Data Nascimento

		variation Variation
			isDefault
			relationship: 39c1e8c9-2513-40c8-904f-c0194e1940ed
			defaultHierarchy: LocalDateTable_e851d384-d207-4aaf-a3cf-9076987bcb99.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Estado Civil'
		dataType: string
		lineageTag: b810b91f-f216-4f98-8b64-2b1432725249
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column 'Num Filhos'
		dataType: int64
		formatString: 0
		lineageTag: 8f5e1835-2243-4968-b2c4-0911946dace1
		summarizeBy: sum
		sourceColumn: Num Filhos

		annotation SummarizationSetBy = Automatic

	column 'Nivel Escolar'
		dataType: string
		lineageTag: 6dbfc2ba-77ed-4e02-9f64-73715cbf47b0
		summarizeBy: none
		sourceColumn: Nivel Escolar

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: fc25c437-e494-4ee8-b036-2220c15ae46d
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: 8c1377eb-0174-4cc7-907f-2cceaac30c36
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column 'FAIXA ETARIA' = ```
			
			IF(dClientes[Idade] <= 12, "Criança",
			IF(dClientes[Idade] <= 18, "Adolescente",
			IF(dClientes[Idade]<= 30,"Adulto 1",
			IF(dClientes[Idade] <65, "Adulto 2", 
			"Idoso"))))
			```
		lineageTag: 49095791-c965-4674-84d6-dc750cfa0b96
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column novazul =
			
			IF(dClientes[Genero] = "Masculino" && dClientes[Idade] >=40,
			"Elegivel",
			"Não Elegivel")
		lineageTag: 3717df27-88d4-4bbc-806d-99df73e7aec5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column diamaes = IF(dClientes[Genero] = "Feminino" && dClientes[Num Filhos] > 0,"Mãe","Ainda não")
		lineageTag: 53990a4c-581f-4c19-94d0-3a89c4d88479
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dClientes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\cvamo\OneDrive - Clei Amorim TECnologia\Escolas\CATEC\Turmas\Arcelormittal\Turma 03 - Acerlomittal - Power BI\bd_basico\Cadastro Clientes.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Plan1_Sheet,{{"Column1", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type any}, {"Column9", type text}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",2),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Linhas Superiores Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Cliente", Int64.Type}, {"Primeiro Nome", type text}, {"Sobrenome", type text}, {"Email", type text}, {"Genero", type text}, {"Data Nascimento", type text}, {"Estado Civil", type text}, {"Num Filhos", Int64.Type}, {"Nivel Escolar", type text}, {"Documento", Int64.Type}, {"Column11", type any}, {"Column12", type any}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado1",{{"ID Cliente", Order.Ascending}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Linhas Classificadas", {{"Data Nascimento", type date}}, "en-US"),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado com Localidade","F","Feminino",Replacer.ReplaceText,{"Genero"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","M","Masculino",Replacer.ReplaceText,{"Genero"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","C","Casado",Replacer.ReplaceText,{"Estado Civil"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2","S","Solteiro",Replacer.ReplaceText,{"Estado Civil"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","D","Divorciado",Replacer.ReplaceText,{"Estado Civil"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído4",{{"Primeiro Nome", Text.Proper, type text}, {"Sobrenome", Text.Proper, type text}}),
				    #"Colunas Mescladas" = Table.CombineColumns(#"Colocar Cada Palavra Em Maiúscula",{"Primeiro Nome", "Sobrenome"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Nome Completo"),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Mescladas",{"Column11", "Column12"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas",{{"ID Cliente", type text}, {"Documento", type text}}),
				    #"Idade Inserida" = Table.AddColumn(#"Tipo Alterado2", "Idade", each Date.From(DateTime.LocalNow()) - [Data Nascimento], type duration),
				    #"Total de Anos Calculado" = Table.TransformColumns(#"Idade Inserida",{{"Idade", each Duration.TotalDays(_) / 365, type number}}),
				    #"Arredondado para Baixo" = Table.TransformColumns(#"Total de Anos Calculado",{{"Idade", Number.RoundDown, Int64.Type}})
				in
				    #"Arredondado para Baixo"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

