table dVendedores
	lineageTag: 5c647db5-142c-4eb6-b329-b5bff58dfa18

	column ID
		dataType: string
		lineageTag: 2976b205-e116-44c4-ae77-fde245f5a274
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 776ff98e-8fd8-4fb9-8b61-69cb1013f699
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column 'Data de Admissão'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7aac010-e6c4-4d71-8789-b3d7275ec0d0
		summarizeBy: none
		sourceColumn: Data de Admissão

		variation Variation
			isDefault
			relationship: 736fea97-3575-4bd4-a178-0d8df119ad30
			defaultHierarchy: LocalDateTable_5d0c55f2-1f75-47e3-b720-2ed791d85a6e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dVendedores = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\cvamo\OneDrive - Clei Amorim TECnologia\Escolas\CATEC\Turmas\Arcelormittal\Turma 03 - Acerlomittal - Power BI\bd_basico\cadastro_vendedores.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", type text}, {"Nome Completo", type text}, {"Data de Admissão", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

