table dClientes
	lineageTag: 35e2ce36-f68b-431a-8043-332486f857d5

	column 'ID Cliente'
		dataType: int64
		formatString: 0
		lineageTag: b10b87b6-0e40-4879-a9a4-7cc05e93694c
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 6997e5cc-5294-4d84-8fac-661a17f7d992
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: 12a2f145-04b4-47ac-a69e-9cec8766f7b6
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86c2a9c0-397c-4f70-9a23-911953f7a2ce
		summarizeBy: none
		sourceColumn: Data Nascimento

		variation Variation
			isDefault
			relationship: 2a737cc4-714a-4f99-9ab2-06d9287e40c1
			defaultHierarchy: LocalDateTable_6e30c11f-65e0-4c44-99d0-adad57233e71.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Num Filhos'
		dataType: int64
		formatString: 0
		lineageTag: 8ebef008-d833-446e-99fc-057d0e69fa68
		summarizeBy: sum
		sourceColumn: Num Filhos

		annotation SummarizationSetBy = Automatic

	column 'Nivel Escolar'
		dataType: string
		lineageTag: 3928378f-67ac-49cd-82e5-e142ad4e0588
		summarizeBy: none
		sourceColumn: Nivel Escolar

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: 6368d589-606c-4d2b-881e-9a5dc2048d15
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: 309332e7-d244-4846-a4b0-93f31d4a4011
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: 8a73d6bb-83fd-4c64-abf3-61e8a5fb2382
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: a81ab1fc-2370-40f5-bb47-fdaf9a34b6f5
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column 'Faixa Etaria' =
			SWITCH(TRUE(),
			dClientes[Idade]<=19, "Jovem",
			dClientes[Idade]<=59, "Adulto",
			"Sênior"
			)
		lineageTag: e54fc7ef-0936-4f47-a854-c7089cfaf34d
		summarizeBy: none
		sortByColumn: 'Numeração Faixa Etária'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Numeração Faixa Etária' =
			SWITCH(TRUE(),
			dClientes[Idade]<=19, 1,
			dClientes[Idade]<=59, 2,
			3
			)
		formatString: 0
		lineageTag: 92444725-5faa-43ad-992e-cc1564d23b33
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Desconto =
			SWITCH(dClientes[Nivel Escolar],
			"Pós Graduação", 0.2,
			"Superior Completo", 0.1,
			"Superior Incompleto", 0.05,
			0
			)
		lineageTag: 4ccac75a-5571-4fa9-bea3-44e77e63213f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dClientes-b296c2e8-6220-4b7b-ace1-9c1c115f0bfc = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\cvamo\OneDrive - Clei Amorim TECnologia\Documentos\03. Treinamentos_Empresas\Arcelormittal\Atividades\Atividade 4\Cadastro Clientes.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Plan1_Sheet,{{"Column1", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type any}, {"Column9", type text}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column11", "Column12"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Documento", type text}, {"Num Filhos", Int64.Type}, {"ID Cliente", Int64.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado1","M","Masculino",Replacer.ReplaceText,{"Genero"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","F","Feminino",Replacer.ReplaceText,{"Genero"}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Valor Substituído1", {{"Data Nascimento", type date}}, "en-US"),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado com Localidade",{"ID Cliente", "Primeiro Nome", "Sobrenome", "Email", "Nivel Escolar", "Genero", "Data Nascimento", "Estado Civil", "Num Filhos", "Documento"}),
				    #"Colunas Mescladas" = Table.CombineColumns(#"Colunas Reordenadas",{"Primeiro Nome", "Sobrenome"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Nome Cliente"),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Colunas Mescladas",{{"Nome Cliente", Text.Proper, type text}}),
				    #"Idade Inserida" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "Idade", each Date.From(DateTime.LocalNow()) - [Data Nascimento], type duration),
				    #"Total de Anos Calculado" = Table.TransformColumns(#"Idade Inserida",{{"Idade", each Duration.TotalDays(_) / 365, type number}}),
				    #"Arredondado para Baixo" = Table.TransformColumns(#"Total de Anos Calculado",{{"Idade", Number.RoundDown, Int64.Type}})
				in
				    #"Arredondado para Baixo"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

