table dLojas
	lineageTag: e04ec9a3-fbee-4033-82f4-4695dc0a27e0

	column 'ID Loja'
		dataType: int64
		formatString: 0
		lineageTag: 537a4559-f075-4747-85d5-332908ef0edd
		summarizeBy: none
		sourceColumn: ID Loja

		annotation SummarizationSetBy = Automatic

	column 'Nome da Loja'
		dataType: string
		lineageTag: ac65c97e-3b4c-41f9-99cf-ffdea420aa62
		summarizeBy: none
		sourceColumn: Nome da Loja

		annotation SummarizationSetBy = Automatic

	column 'Nome Gerente'
		dataType: string
		lineageTag: 0ad6dc94-c664-4326-925b-9d3ed2479128
		summarizeBy: none
		sourceColumn: Nome Gerente

		annotation SummarizationSetBy = Automatic

	column 'Quantidade Colaboradores'
		dataType: int64
		formatString: 0
		lineageTag: 88e61080-2707-4c7b-8cab-87d7ad53eb61
		summarizeBy: sum
		sourceColumn: Quantidade Colaboradores

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 005765b9-6221-454a-8f86-f5ca4ef2578f
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'id Localidade'
		dataType: int64
		formatString: 0
		lineageTag: acc11b1c-3f09-4798-9ebe-345b20f1ab5b
		summarizeBy: sum
		sourceColumn: id Localidade

		annotation SummarizationSetBy = Automatic

	column 'Documento Gerente'
		dataType: string
		lineageTag: 09dce5a2-123a-4d76-bd7d-726cad47c7e3
		summarizeBy: none
		sourceColumn: Documento Gerente

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 3d22c4e5-e9e3-4cff-9783-5e0ac7a9c7bb
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column Continente
		dataType: string
		lineageTag: b9a4b24f-5fb1-4f2d-af61-e90b660235d2
		summarizeBy: none
		sourceColumn: Continente

		annotation SummarizationSetBy = Automatic

	partition dLojas-a5e61059-2548-466a-ada9-ee1233b4acdb = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\cvamo\OneDrive - Clei Amorim TECnologia\Documentos\03. Treinamentos_Empresas\Arcelormittal\Atividades\Atividade 4\Cadastro Lojas.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Plan1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Loja", Int64.Type}, {"Nome da Loja", type text}, {"Quantidade Colaboradores", Int64.Type}, {"Tipo", type text}, {"id Localidade", Int64.Type}, {"Gerente Loja", type text}, {"Documento Gerente", type text}}),
				    #"Texto Extraído Após o Delimitador" = Table.TransformColumns(#"Tipo Alterado", {{"Nome da Loja", each Text.AfterDelimiter(_, " "), type text}}),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Texto Extraído Após o Delimitador", "Nome Gerente", each let splitGerenteLoja = Splitter.SplitTextByDelimiter(", ", QuoteStyle.None)([Gerente Loja]) in Text.Combine({splitGerenteLoja{1}?, " ", splitGerenteLoja{0}?}), type text),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Personalizada Adicionada",{"Gerente Loja"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"ID Loja", "Nome da Loja", "Nome Gerente", "Quantidade Colaboradores", "Tipo", "id Localidade", "Documento Gerente"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Reordenadas", {"id Localidade"}, dLocalidades, {"ID Localidade"}, "CadastroLocalidades", JoinKind.LeftOuter),
				    #"CadastroLocalidades Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "CadastroLocalidades", {"País", "Continente"}, {"País", "Continente"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"CadastroLocalidades Expandido","Oceania","Austrália",Replacer.ReplaceText,{"Continente"})
				in
				    #"Valor Substituído"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

